"""first migration

Revision ID: 89209a4145af
Revises: 
Create Date: 2019-08-20 20:36:36.835714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89209a4145af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
